# Microprofile server properties
server:
  port: 8081
  host: 0.0.0.0

# Datasource properties
javax:
  sql:
    DataSource:
      H2DataSource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        dataSource:
          url: jdbc:h2:mem:test;INIT=RUNSCRIPT FROM 'classpath:create-table.ddl'
          user: sa
          password:
      AtpDataSource:
        dataSourceClassName: oracle.jdbc.pool.OracleDataSource
        dataSource:
          url: jdbc:oracle:thin:@sandbox_high?TNS_ADMIN=C:/Work/05_oci/wallets/Wallet_SANDBOX
          user: sandbox
          password: Passw0rd12345
        connectionTimeout: 5000

# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics:
  rest-request:
    enabled: false

cors:
  paths:
    - path-pattern: /webauthn/attestation/options/{*}
      allow-origins: ["*"]
      allow-methods: ["*"]
    - path-pattern: /webauthn/attestation/result
      allow-origins: ["*"]
      allow-methods: ["*"]
    - path-pattern: /webauthn/assertion/options/{*}
      allow-origins: ["*"]
      allow-methods: ["*"]
    - path-pattern: /webauthn/assertion/result
      allow-origins: ["*"]
      allow-methods: ["*"]
    - path-pattern: /
      allow-methods: ["GET", "HEAD", "OPTIONS", "POST"]